# -*- coding: utf-8 -*-
"""18IT044_DS_PR2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lDJYf-h3khQ9Qb5i7sq_6mMyZKU4-vHG
"""

import pandas as pd
import numpy as np

# Importing the dataset
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

from sklearn.preprocessing import LabelEncoder
country = LabelEncoder()
X[:,0] = country.fit_transform(X[:,0])
print(X)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

# Taking care of missing data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:6])
X[:, 1:6] = imputer.transform(X[:, 1:6])
print(X)

from sklearn import preprocessing 
normal = preprocessing.normalize(X)
np.set_printoptions(suppress=True)
print(normal)

from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()
standardized_data = standard_scaler.fit_transform(X)
print(standardized_data)